package emit_test

import (
	"strings"
	"testing"

	"github.com/jsazanami-del/pg2protobuf-generator/internal/emit"
	"github.com/jsazanami-del/pg2protobuf-generator/internal/lock"
)

func TestRenderFile(t *testing.T) {
	ir := &lock.IR{Files: []*lock.ProtoFile{{
		Path:      "public/users.proto",
		Package:   "db.v1.public",
		GoPackage: "github.com/example/app/gen/proto/db/v1/public",
		Imports:   []string{"buf/validate/validate.proto", "google/protobuf/timestamp.proto"},
		Messages: []*lock.IRMessage{{
			Name: "Users",
			Fields: []*lock.IRField{
				{Type: "int64", Name: "id", Number: 1},
				{Type: "string", Name: "email", Number: 2, Options: []string{"(buf.validate.field).string.email = true"}},
				{Type: "google.protobuf.Timestamp", Name: "created_at", Number: 3},
				{Label: "optional", Type: "string", Name: "nickname", Number: 4},
			},
			ReservedNumbers: []int{5},
			ReservedNames:   []string{"legacy_col"},
		}},
	}}}
	got, err := emit.Render(ir)
	if err != nil {
		t.Fatal(err)
	}
	body := got["public/users.proto"]
	for _, want := range []string{
		"// Code generated by pg2proto. DO NOT EDIT.",
		"package db.v1.public;",
		`option go_package = "github.com/example/app/gen/proto/db/v1/public";`,
		"message Users {",
		"int64 id = 1;",
		"(buf.validate.field).string.email = true",
		"optional string nickname = 4;",
		"reserved 5;",
		`reserved "legacy_col";`,
	} {
		if !strings.Contains(body, want) {
			t.Fatalf("missing %q in\n%s", want, body)
		}
	}
}
