package engine

import (
	"context"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgtype"

	"github.com/jsazanami-del/pg2protobuf-generator/internal/catalog"
	"github.com/jsazanami-del/pg2protobuf-generator/internal/config"
	"github.com/jsazanami-del/pg2protobuf-generator/internal/emit"
	"github.com/jsazanami-del/pg2protobuf-generator/internal/lock"
	"github.com/jsazanami-del/pg2protobuf-generator/internal/mapping"
)

type Options struct {
	Conn           string
	Schemas        []string
	Out            string
	OutSet         bool
	Config         string
	LockFile       string
	DryRun         bool
	Force          bool
	Prune          bool
	Exclude        []string
	StrictTypes    bool
	StrictTypesSet bool
	Snapshot       *catalog.Snapshot
	Stdout         io.Writer
}

type Result struct {
	Files    map[string]string
	Lock     *lock.File
	Breaking []string
	Out      string
}

func Run(ctx context.Context, opt Options) (*Result, error) {
	if len(opt.Schemas) == 0 {
		opt.Schemas = []string{"public"}
	}
	if opt.LockFile == "" {
		opt.LockFile = ".pg2proto.lock"
	}
	if opt.Config == "" {
		opt.Config = ".pg2proto.yaml"
	}
	if opt.Stdout == nil {
		opt.Stdout = os.Stdout
	}

	cfg, err := config.Load(opt.Config)
	if err != nil {
		return nil, err
	}
	var strictTypes *bool
	if opt.StrictTypesSet {
		v := opt.StrictTypes
		strictTypes = &v
	}
	cfg.MergeFlags(opt.Exclude, strictTypes)
	if err := cfg.ValidateProto(); err != nil {
		return nil, err
	}

	snap := opt.Snapshot
	var conn *pgx.Conn
	if snap == nil {
		dsn := opt.Conn
		if dsn == "" {
			dsn = os.Getenv("DATABASE_URL")
		}
		if dsn == "" {
			return nil, fmt.Errorf("database connection is required (--conn or DATABASE_URL)")
		}
		conn, err = pgx.Connect(ctx, dsn)
		if err != nil {
			return nil, fmt.Errorf("connect: %w", err)
		}
		defer conn.Close(ctx)
		snap, err = catalog.Load(ctx, conn, opt.Schemas)
		if err != nil {
			return nil, err
		}
	}
	filterSnapshot(snap, cfg)

	var resolver mapping.TypeResolver = pgtype.NewMap()
	var loader mapping.TypeLoader
	if conn != nil {
		resolver = conn.TypeMap()
		loader = pgxLoader{ctx: ctx, conn: conn}
	}

	mapped, err := mapping.Apply(snap, cfg, resolver, loader)
	if err != nil {
		return nil, err
	}

	old, err := lock.Load(opt.LockFile)
	if err != nil {
		return nil, err
	}
	assigned := lock.Assign(old, mapped, cfg)
	files, err := emit.Render(assigned.IR)
	if err != nil {
		return nil, err
	}
	return &Result{Files: files, Lock: assigned.Lock, Breaking: assigned.Breaking, Out: resolveOut(opt, cfg)}, nil
}

func resolveOut(opt Options, cfg *config.Config) string {
	if opt.OutSet {
		if opt.Out != "" {
			return opt.Out
		}
		return "./proto"
	}
	if cfg != nil && cfg.Proto.Out != "" {
		return cfg.Proto.Out
	}
	if opt.Out != "" {
		return opt.Out
	}
	return "./proto"
}

func outputDir(opt Options, res *Result) string {
	if res != nil && res.Out != "" {
		return res.Out
	}
	if opt.Out != "" {
		return opt.Out
	}
	return "./proto"
}

func Write(opt Options, res *Result) error {
	if opt.DryRun {
		for _, pathName := range sortedKeys(res.Files) {
			fmt.Fprintf(opt.Stdout, "=== %s ===\n%s", pathName, res.Files[pathName])
			if !strings.HasSuffix(res.Files[pathName], "\n") {
				fmt.Fprintln(opt.Stdout)
			}
		}
		return nil
	}
	out := outputDir(opt, res)
	if err := os.MkdirAll(out, 0o755); err != nil {
		return err
	}
	for relPath, body := range res.Files {
		full := filepath.Join(out, filepath.FromSlash(relPath))
		if err := os.MkdirAll(filepath.Dir(full), 0o755); err != nil {
			return err
		}
		if err := os.WriteFile(full, []byte(body), 0o644); err != nil {
			return err
		}
	}
	if err := lock.Write(opt.LockFile, res.Lock); err != nil {
		return err
	}
	if opt.Prune {
		return prune(out, res.Files)
	}
	return nil
}

func prune(out string, keep map[string]string) error {
	return filepath.WalkDir(out, func(p string, d os.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if d.IsDir() {
			return nil
		}
		if filepath.Ext(p) != ".proto" {
			return nil
		}
		rel, err := filepath.Rel(out, p)
		if err != nil {
			return err
		}
		key := filepath.ToSlash(rel)
		if _, ok := keep[key]; ok {
			return nil
		}
		data, err := os.ReadFile(p)
		if err != nil {
			return err
		}
		if !strings.Contains(string(data), "Code generated by pg2proto") {
			return nil
		}
		return os.Remove(p)
	})
}

func filterSnapshot(snap *catalog.Snapshot, cfg *config.Config) {
	var rels []catalog.Relation
	for _, r := range snap.Relations {
		if cfg.SelectsRelation(r.Schema, r.Name) {
			rels = append(rels, r)
		}
	}
	snap.Relations = rels
}

func sortedKeys(m map[string]string) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}

type pgxLoader struct {
	ctx  context.Context
	conn *pgx.Conn
}

func (l pgxLoader) LoadType(typeName string) (*pgtype.Type, error) {
	return l.conn.LoadType(l.ctx, typeName)
}
